
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ jar_workflow-aws ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant excution permission for gradlew
      run: chmod +x gradlew
    - name: Build with gradle  
      run: ./gradlew build
    - name : Create Timestamp for Version Info
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
       format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Make Artifact Available
      uses: actions/upload-artifact@v2
      with:
       name: "Artifact-${{steps.time.outputs.time}}"
       path: build/libs
       retention-days: 5
      
